[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = " nosniff",
    Cache-control = "no-store,max-age=0",
    Referrer-Policy = "no-referrer",
    X-Frame-Options = "DENY",
    X-XSS-Protection = "1; mode=block",
    Permissions-Policy = "geolocation=(self), midi=(), sync-xhr=(), camera=(), microphone=(), magnetometer=(), gyroscope=(), fullscreen=(), payment=()"


    